insert into Treatments (treatmentType, title, description) values ('Medrox', 'H.J. Harkins Company, Inc.', 'est lacinia nisi venenatis tristique');
insert into Treatments (treatmentType, title, description) values ('Equate Nicotine', 'Wal-Mart Stores Inc', 'in libero ut');
insert into Treatments (treatmentType, title, description) values ('Headache Relief', 'SMART SENSE (Kmart)', 'ante ipsum primis');
insert into Treatments (treatmentType, title, description) values ('Se-Tan PLUS', 'Seton Pharmaceuticals', 'tincidunt ante vel');
insert into Treatments (treatmentType, title, description) values ('Diarrhea', 'Washington Homeopathic Products', 'mi in porttitor pede justo eu');
insert into Treatments (treatmentType, title, description) values ('Lotensin HCT', 'Validus Pharmaceuticals LLC', 'luctus rutrum nulla tellus in');
insert into Treatments (treatmentType, title, description) values ('Methocarbamol', 'American Health Packaging', 'adipiscing elit proin risus praesent');
insert into Treatments (treatmentType, title, description) values ('Testosterone Enanthate', 'Watson Laboratories, Inc.', 'ac tellus semper interdum mauris');
insert into Treatments (treatmentType, title, description) values ('Diltiazem Hydrochloride', 'American Health Packaging', 'vehicula consequat morbi');
insert into Treatments (treatmentType, title, description) values ('Pleo Fort', 'Sanum Kehlbeck GmbH & Co. KG', 'proin risus praesent');
insert into Treatments (treatmentType, title, description) values ('Healthy Accents Night Time Cough', 'DZA Brands LLC', 'maecenas pulvinar lobortis est');
insert into Treatments (treatmentType, title, description) values ('Terrestristat', 'Energique, Inc.', 'suscipit a feugiat et');
insert into Treatments (treatmentType, title, description) values ('DHEA Forte', 'BioActive Nutritionals, Inc.', 'ante ipsum primis in faucibus');
insert into Treatments (treatmentType, title, description) values ('Pioglitazone Hydrochloride', 'Aurobindo Pharma Limited', 'viverra pede ac diam');
insert into Treatments (treatmentType, title, description) values ('Treatment Set TS342034', 'Antigen Laboratories, Inc.', 'integer aliquet massa id lobortis convallis');
insert into Treatments (treatmentType, title, description) values ('MEDROX', 'Preferred Pharmaceuticals, Inc.', 'imperdiet nullam orci');
insert into Treatments (treatmentType, title, description) values ('Night Time Cherry', 'Nash-Finch Company', 'cum sociis natoque penatibus et');
insert into Treatments (treatmentType, title, description) values ('Fluocinonide', 'Glenmark Generics Inc., USA', 'mauris lacinia sapien quis');
insert into Treatments (treatmentType, title, description) values ('Fluocinolone Acetonide', 'GW Laboratories, Inc.', 'aliquam augue quam sollicitudin vitae consectetuer');
insert into Treatments (treatmentType, title, description) values ('buprenorphine hydrochloride', 'Hi-Tech Pharmacal Co., Inc.', 'id luctus nec');
insert into Treatments (treatmentType, title, description) values ('Neutrogena Wet Skin Kids', 'Neutrogena Corporation', 'odio condimentum id luctus nec');
insert into Treatments (treatmentType, title, description) values ('La Roche', 'L''Oreal USA Products Inc', 'id sapien in');
insert into Treatments (treatmentType, title, description) values ('Ibuprofen', 'Advil', 'nulla neque libero');
insert into Treatments (treatmentType, title, description) values ('Cough DM', 'Shopko Stores Operating', 'sed accumsan felis');
insert into Treatments (treatmentType, title, description) values ('24 Hour Allergy', 'LIVE BETTER', 'urna ut tellus nulla ut erat');
