insert into Treatments (treatmentID, treatmentType, title, description) values (168, 'Guanfacine', 'Carilion Materials Management', 'eleifend quam a odio in');
insert into Treatments (treatmentID, treatmentType, title, description) values (261, 'Colgate', 'Mission Hills, S.A. de C.V.', 'turpis adipiscing lorem vitae mattis');
insert into Treatments (treatmentID, treatmentType, title, description) values (269, 'Escitalopram Oxalate', 'Mylan Pharmaceuticals Inc.', 'rutrum rutrum neque aenean auctor');
insert into Treatments (treatmentID, treatmentType, title, description) values (117, 'SolMate', 'Prime Packaging, Inc.', 'maecenas tristique est et tempus');
insert into Treatments (treatmentID, treatmentType, title, description) values (173, 'Scrub Pine', 'Nelco Laboratories, Inc.', 'donec diam neque vestibulum eget');
insert into Treatments (treatmentID, treatmentType, title, description) values (113, 'Total White Brightening', 'YZY Inc', 'turpis adipiscing lorem vitae mattis');
insert into Treatments (treatmentID, treatmentType, title, description) values (116, 'Magnesium Chloride', 'The Torrance Company', 'nisi volutpat eleifend donec ut');
insert into Treatments (treatmentID, treatmentType, title, description) values (195, 'PHENYTOIN SODIUM', 'SUN PHARMACEUTICAL INDUSTRIES LIMITED', 'porttitor id consequat in consequat');
insert into Treatments (treatmentID, treatmentType, title, description) values (128, 'Meloxicam', 'Apotex Corp.', 'lacinia erat vestibulum sed magna');
insert into Treatments (treatmentID, treatmentType, title, description) values (128, 'donepezil hydrochloride', 'Cadila Healthcare Limited', 'penatibus et magnis dis parturient');
insert into Treatments (treatmentID, treatmentType, title, description) values (238, 'Anti-Bacterial Deep Cleansing Hand', 'Bath & Body Works, Inc.', 'aliquam non mauris morbi non');
insert into Treatments (treatmentID, treatmentType, title, description) values (289, 'Amar Petroleum', 'Amar Remedies Limited', 'volutpat in congue etiam justo');
insert into Treatments (treatmentID, treatmentType, title, description) values (182, 'Brussels Sprout', 'Nelco Laboratories, Inc.', 'in magna bibendum imperdiet nullam');
insert into Treatments (treatmentID, treatmentType, title, description) values (290, 'Guanfacine', 'Golden State Medical Supply, Inc.', 'semper porta volutpat quam pede');
insert into Treatments (treatmentID, treatmentType, title, description) values (286, 'Piperacillin and Tazobactam', 'Hospira, Inc', 'velit nec nisi vulputate nonummy');
insert into Treatments (treatmentID, treatmentType, title, description) values (278, 'Doxazosin', 'Major Pharmaceuticals', 'id nisl venenatis lacinia aenean');
insert into Treatments (treatmentID, treatmentType, title, description) values (257, 'Testosterone Cypionate', 'Watson Laboratories, Inc.', 'congue etiam justo etiam pretium');
insert into Treatments (treatmentID, treatmentType, title, description) values (281, 'ADSOL Red Cell Preservation Solution System in Plastic Container (PL 146 Plastic)', 'Fenwal, Inc.', 'justo lacinia eget tincidunt eget');
insert into Treatments (treatmentID, treatmentType, title, description) values (214, 'Loratadine', 'Novartis Consumer Health, Inc.', 'rutrum rutrum neque aenean auctor');
insert into Treatments (treatmentID, treatmentType, title, description) values (253, 'Pancuronium Bromide', 'Teva Parenteral Medicines, Inc.', 'ultrices posuere cubilia curae duis');
insert into Treatments (treatmentID, treatmentType, title, description) values (265, 'alcohol', 'Sion Biotext Medical Ltd', 'ipsum ac tellus semper interdum');
insert into Treatments (treatmentID, treatmentType, title, description) values (272, 'Longleaf Pine', 'Nelco Laboratories, Inc.', 'volutpat convallis morbi odio odio');
insert into Treatments (treatmentID, treatmentType, title, description) values (221, 'OxyContin', 'Purdue Pharma LP', 'aliquet massa id lobortis convallis');
insert into Treatments (treatmentID, treatmentType, title, description) values (124, 'BUCKWHEAT', 'Allergy Laboratories, Inc.', 'fermentum justo nec condimentum neque');
insert into Treatments (treatmentID, treatmentType, title, description) values (121, 'Extra Strength Pain Reliever PM', 'FRED''S, INC.', 'duis aliquam convallis nunc proin');
